#!/usr/bin/env python3
"""
OpenClaw — Generate a full Markdown document report.

Usage:
  python ocr_report.py scan.png
  python ocr_report.py invoice.png --type invoice --output report.md
  python ocr_report.py doc.png --find "Total,Date,Reference" --output report.md
"""
import argparse
import base64
import json
import sys
from pathlib import Path

import httpx


def main():
    parser = argparse.ArgumentParser(description="OpenClaw document report")
    parser.add_argument("file")
    parser.add_argument("--type",    default="general",
                        choices=["general","invoice","contract","receipt"])
    parser.add_argument("--find",    default="", help="Comma-separated terms to search for")
    parser.add_argument("--mcp-url", default="http://localhost:8000/mcp")
    parser.add_argument("--api-key", default="")
    parser.add_argument("--output",  default="")
    args = parser.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"Error: file not found: {path}", file=sys.stderr)
        sys.exit(1)

    b64   = base64.b64encode(path.read_bytes()).decode()
    hdrs  = {"Content-Type": "application/json"}
    if args.api_key:
        hdrs["Authorization"] = f"Bearer {args.api_key}"

    custom_map = {
        "invoice":  "Extract as JSON: invoice_number, date, vendor, client, total, tax, currency.",
        "contract": "Extract: parties, effective date, jurisdiction, key obligations, expiry date.",
        "receipt":  "Extract: merchant, date, items, subtotal, tax, total.",
        "general":  "",
    }
    custom = custom_map.get(args.type, "")
    mode   = "freeform" if custom else "document"
    terms  = [t.strip() for t in args.find.split(",") if t.strip()]

    print(f"Generating {args.type} report for {path.name}...", file=sys.stderr)

    _id = 1
    sections = {}

    with httpx.Client(timeout=400.0) as client:
        client.post(args.mcp_url, headers=hdrs, json={
            "jsonrpc":"2.0","id":_id,"method":"initialize",
            "params":{"protocolVersion":"2025-03-26",
                      "clientInfo":{"name":"openclaw-report","version":"1.0"},
                      "capabilities":{}},
        }); _id += 1
        client.post(args.mcp_url, headers=hdrs, json={
            "jsonrpc":"2.0","method":"notifications/initialized",
        })

        def _ocr(tool_args):
            nonlocal _id
            _id += 1
            r = client.post(args.mcp_url, headers=hdrs, json={
                "jsonrpc":"2.0","id":_id,"method":"tools/call",
                "params":{"name":"ocr_image","arguments":{**tool_args,"auto_fallback":True}},
            })
            result = r.json().get("result",{})
            return "\n".join(
                c.get("text","") for c in result.get("content",[]) if c.get("type")=="text"
            ), result.get("meta",{})

        # Main extraction
        sections["main"], meta = _ocr({
            "image_base64": b64, "filename": path.name,
            "mode": mode, "custom_prompt": custom,
        })
        print(f"  Main: {meta.get('backend','?')} {meta.get('duration_ms',0)}ms", file=sys.stderr)

        # Visual description
        sections["description"], _ = _ocr({
            "image_base64": b64, "filename": path.name, "mode": "describe",
        })

        # Find terms
        sections["finds"] = {}
        for term in terms:
            txt, _ = _ocr({
                "image_base64": b64, "filename": path.name,
                "mode": "find", "find_term": term,
            })
            if txt.strip():
                sections["finds"][term] = txt.strip()

    # Build Markdown report
    lines = [
        f"# ⚡ OpenClaw Report — {path.name}",
        f"",
        f"**Type:** {args.type}  |  **Backend:** {meta.get('backend','?')}  "
        f"|  **Duration:** {meta.get('duration_ms',0)}ms",
        f"",
        f"---",
        f"",
        f"## Visual Description",
        f"",
        sections["description"],
        f"",
        f"---",
        f"",
        f"## Extracted Content",
        f"",
        sections["main"],
        f"",
    ]

    if sections["finds"]:
        lines += ["---", "", "## Term Search Results", ""]
        for term, ctx in sections["finds"].items():
            lines += [f"### `{term}`", ctx, ""]

    lines += ["---", "", "*Generated by OpenClaw via lightning-ocr MCP*"]
    report = "\n".join(lines)

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"Report saved to: {args.output}", file=sys.stderr)
    else:
        print(report)


if __name__ == "__main__":
    main()